### PR TITLE
[#173] Reroute to concepts page after concept uuid is deleted

### PR DESCRIPTION
**Pull request by loiscodes**
Created function to call concept remove method and redirect to the list of concepts

### CODE REVIEW

**Review by dipasqualew — CHANGES_REQUESTED** [review]
Thank you so much for the PR.

I think the function does exactly what needs to be done. However, would you be so kind to check it by extending the cypress test related to this page?

There is already a test that at the end of its workflow deletes the concept; so I believe the only change required after deletion is to check that the url matches `/concepts`:
https://github.com/photion/web-admin/blob/master/cypress/integration/pages/concepts/_uuid.spec.ts#L188

**Comment by loiscodes** [comment]
Noticed the save concept was merged into master. Fixing my branch right now to add that commit

**Comment by dipasqualew** [comment]
Thanks @loiscodes - You don't need to rebase, I can just squash the commit from this end!

**Comment by dipasqualew** [comment]
Closes in favour of #197

**Pull request closed without merging**
