### PR TITLE
Refactor SCSS folder structure and break classes into files

### LINKED ISSUE #199: feat: Refactor SASS structure
**Is your feature request related to a problem? Please describe.**
Having in mind that components could and will scale, we could take advantage of the SCSS features and break our styles into atom components.

**Describe the solution you'd like**
Break our styles into a common approach.

### PR DESCRIPTION
**Pull request by yurianxdev**
This is a common approach that I use in my projects, but it only uses the structure we need so far... Should I add the whole structure? @dipasqualew 

Closes #199.

### CODE REVIEW

**Comment by dipasqualew** [comment]
Thanks @yurianxdev! I agree with the new structure.

What do you mean with "whole structure"? Seems like you migrated all the current scss?

**Comment by yurianxdev** [comment]
Have I migrated our whole SCSS we have so far? Yes, but the folder structure still incomplete if our styles keep growing (it will). So I can include empty files as a reference, even if we are not using it yet, I should?

**Comment by yurianxdev** [comment]
This is the way I use SASS in all my projects:

Screen Shot 2020-10-17 at 17 08 22

**Comment by dipasqualew** [comment]
Sounds like a great idea! Please proceed 🙂

**Comment by yurianxdev** [comment]
Ready :)

**Review by dipasqualew — APPROVED** [review]
Well done!

**Pull request merged**
